# Release Drafter Configuration
# Automatically generates release notes from merged PRs
# Uses Keep a Changelog format: https://keepachangelog.com/
# See: https://github.com/release-drafter/release-drafter

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

# Disable default '## ' prefix since our titles include '###'
category-template: '$TITLE'

# Group PRs by label into Keep a Changelog categories
# Uses semantic labels only (not component labels) to prevent duplicates
# Order matters - PRs appear in ALL matching categories, so labels must be mutually exclusive
categories:
  # Keep a Changelog standard sections
  - title: '### Breaking Changes'
    labels:
      - 'breaking'
  - title: '### Added'
    labels:
      - 'enhancement'
  - title: '### Changed'
    labels:
      - 'refactor'
  - title: '### Deprecated'
    labels:
      - 'deprecated'
  - title: '### Removed'
    labels:
      - 'removed'
  - title: '### Fixed'
    labels:
      - 'bug'
  - title: '### Security'
    labels:
      - 'security'
  # Additional useful sections (not in Keep a Changelog but valuable)
  - title: '### Performance'
    labels:
      - 'optimization'
  - title: '### Documentation'
    labels:
      - 'documentation'
  - title: '### Dependencies'
    labels:
      - 'dependencies'
  - title: '### CI/CD'
    labels:
      - 'automation'
      - 'github-actions'

# Exclude certain labels from release notes
exclude-labels:
  - 'duplicate'
  - 'invalid'
  - 'wontfix'
  - 'stale'
  - 'review:deep'
  - 'review:quick'

# Format for each change entry
change-template: '- $TITLE ([#$NUMBER]($URL))'
change-title-escapes: '\<*_&'

# Auto-apply semantic labels based on conventional commit prefixes
# This ensures each PR gets exactly ONE semantic label for categorization
autolabeler:
  - label: 'breaking'
    title:
      - '/^.*!:/'
      - '/BREAKING CHANGE/'
    body:
      - '/BREAKING CHANGE/'
  - label: 'enhancement'
    title:
      - '/^feat(\(.+\))?:/'
  - label: 'bug'
    title:
      - '/^fix(\(.+\))?:/'
  - label: 'documentation'
    title:
      - '/^docs(\(.+\))?:/'
  - label: 'refactor'
    title:
      - '/^refactor(\(.+\))?:/'
  - label: 'optimization'
    title:
      - '/^perf(\(.+\))?:/'
  - label: 'automation'
    title:
      - '/^ci(\(.+\))?:/'
      - '/^build(\(.+\))?:/'
  - label: 'security'
    title:
      - '/^security(\(.+\))?:/'

# Determine version bump from labels
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'documentation'
      - 'dependencies'
      - 'github-actions'
      - 'automation'
      - 'security'
      - 'optimization'
      - 'refactor'
  default: patch

# Release notes template (Keep a Changelog format)
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
