title: "[Idea]: "
labels: ["enhancement", "idea"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea! Help us understand what problem you're solving and your proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Need
      description: What problem does this idea solve? What need does it address?
      placeholder: "I'm frustrated when... I need a way to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Idea
      description: Describe your idea clearly
      placeholder: "I think it would be great if..."
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: Expected Benefit
      description: How would this improve the plugin?
      placeholder: "I would benefit from this because..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you thought of other ways to achieve this?
      placeholder: "I've also considered..."
    validations:
      required: false