title: "[Idea] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea! Help us understand your suggestion.

  - type: textarea
    id: idea
    attributes:
      label: Idea Description
      description: Describe your idea clearly
      placeholder: I think it would be great if...
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: Expected Benefit
      description: How would this improve the plugin?
      placeholder: This would help users by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you thought of other ways to achieve this?
      placeholder: Instead of this, we could also...
    validations:
      required: false
